exp4j = 0.4.8
h2 = 1.4.200
hikaricp = 5.0.1
jdbi = 3.36.0
mariadb = 3.1.0
mysql = 8.0.31
postgresql = 42.5.1
slf4j = 1.7.35
sqlite = 3.40.0.0
jdbi.antlr = 3.5.2
jdbi.caffeine = 2.9.1
jdbi.geantyref = 1.3.13
jdbi.st4 = 4.3.1